# ===================================================================
#      Smart WebView v8 - Main Configuration File (Lorenzo VJGames)
# ===================================================================

build.application.id=com.vjgames.lorenzooaventureiro
build.version.code=10
build.version.name=9.0.2

build.sdk.compile=34
build.sdk.min=24

debug.mode=false

app.url=https://vercel.app
offline.url=file:///android_asset/web/offline.html
search.url=https://google.com
external.url.exception.list=mgks.dev,mgks.github.io,lorenzo-o-aventureiro-game.vercel.app

# Anúncios e Recursos de Mídia Desativados para Limpeza de Permissões na Google Play
plugins.admob=false
admob.banner=false
admob.interstitial=false
admob.rewarded=false

feature.custom.css=false
feature.copy.paste=true
feature.pull.refresh=false
feature.progress.bar=false
feature.zoom=false
feature.save.form=false
feature.open.external.urls=true
feature.chrome.tabs=true
behavior.back.exits=false
feature.exit.dialog=true

# Permissões Limpas na Inicialização (Sem chamadas de Storage/Localização)
permissions.on.launch=NOTIFICATIONS

security.verify.ssl=false
security.block.screenshots=false
security.accept.thirdparty.cookies=true

# Interface Forçada em Modo Horizontal (Landscape) para o Jogo
ui.orientation=2
ui.layout=0
ui.fullscreen=true
ui.drawer.header=false
ui.splash.extend=false

agent.postfix.enabled=true
agent.postfix.value=SWVAndroid
agent.override.enabled=false

analytics.gtag.id=G-7XXC1C7CRQ

# CORREÇÃO CRÍTICA: Desativado todos os plugins nativos pesados para evitar erros de compilação Java
plugins.enabled=
plugins.playground.enabled=false

rating.install.days=3
rating.launch.times=10
rating.remind.interval=2
biometric.trigger.launch=false
