// Top-level build file where you can add configuration options common to all sub-projects/modules.

ext {
	targetCompatibility = 1.8
}

buildscript {
	repositories {
		google()
		mavenCentral()
	}
	dependencies {
		// CORREÇÃO: Versão oficial, estável e perfeitamente compatível com o Gradle 8.4 e o motor Smart WebView v8
		classpath 'com.android.tools.build:gradle:8.2.2'
	}
}

allprojects {
	repositories {
		google()
		mavenCentral()
	}
}
