# For more details on how to configure your build environment visit
# http://gradle.org
#
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx1024m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
#
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://gradle.org
# org.gradle.parallel=true

# Configuração Otimizada de Memória para Estabilidade no Servidor Ubuntu
org.gradle.jvmargs=-Xmx2048M -Dkotlin.daemon.jvm.options="-Xmx2048M"

# Suporte ao Ecossistema Moderno do AndroidX e APIs Antigas
android.useAndroidX=true
android.debug.obsoleteApi=true

# Geração de Recursos Compatível com o Motor Clássico Smart WebView V8
android.nonTransitiveRClass=false
android.nonFinalResIds=false

# Exibe Avisos Detalhados no Log de Execução do Pipeline
org.gradle.warning.mode=all

# CORREÇÃO DEFINITIVA: Desativado o Configuration Cache para evitar quebras no GitHub Actions
org.gradle.unsafe.configuration-cache=false
