/*
  Smart WebView v8 - Versão de Produção Estabilizada para GitHub Actions
  https://github.com
  MIT License — https://opensource.org  
*/

plugins {
	id 'com.android.application'
}

android {
	// O script do GitHub Actions irá reescrever esta linha para com.vjgames.lorenzooaventureiro
	namespace 'mgks.os.swv'
	compileSdk 34

	defaultConfig {
		applicationId 'mgks.os.swv'
		minSdk 24
		targetSdk 34
		versionCode 10
		versionName "9.0.2"
		multiDexEnabled true
	}

	buildTypes {
		release {
			// DESATIVADO: Evita que o compilador do GitHub quebre por falta de ficheiros Proguard nativos
			minifyEnabled false
			shrinkResources false
			proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
		}
	}

	buildFeatures {
		buildConfig true
	}

	compileOptions {
		sourceCompatibility JavaVersion.VERSION_17
		targetCompatibility JavaVersion.VERSION_17
	}
}

dependencies {
	implementation fileTree(include: ['*.jar'], dir: 'libs')
	
	// Bibliotecas Base Core de Estabilidade
	implementation 'androidx.appcompat:appcompat:1.6.1'
	implementation 'com.google.android.material:material:1.9.0'
	implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
	implementation 'androidx.multidex:multidex:2.0.1'
	
	// Recursos de Navegação WebView Nativos
	implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
	implementation 'androidx.browser:browser:1.5.0'
	
	// Plugins nativos básicos integrados (Versões estáveis em Gradle)
	implementation 'com.journeyapps:zxing-android-embedded:4.3.0'
	implementation 'androidx.biometric:biometric:1.1.0'
}
