name: Build Smart WebView v8 AAB Autossinado

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código Nativo
      uses: actions/checkout@v4.2.2

    - name: Configurar ambiente Java JDK 17
      uses: actions/setup-java@v4.5.0
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Configurar Android SDK e Aceitar Licenças
      uses: android-actions/setup-android@v3.2.1

    - name: Garantir Permissões do Compilador
      run: |
        chmod +x gradlew
        mkdir -p "$ANDROID_HOME/licenses" || true
        echo "24a335a4f57f80877430e4ae15220d914f646721" > "$ANDROID_HOME/licenses/android-sdk-license" || true

    - name: Correção de Arquitetura de Namespace e Recursos Duplicados
      run: |
        # 1. Corrige o Manifesto removendo a tag antiga package para evitar conflitos nativos
        sed -i 's/package="mgks.os.swv"//g' app/src/main/AndroidManifest.xml

        # 2. Deleta o arquivo ads.xml para evitar a duplicação de strings do AdMob com o seu strings.xml
        rm -f app/src/main/res/values/ads.xml || true

        # 3. RESOLUÇÃO DO ERRO DA CLASSE R: 
        # Força o Gradle a usar o namespace original para compilar as classes Java perfeitamente,
        # mas altera o ID de saída do aplicativo para o seu ID oficial do Lorenzo.
        sed -i 's/namespace .*/namespace "mgks.os.swv"/g' app/build.gradle
        sed -i 's/applicationId .*/applicationId "com.lorenzo.aventureiro"/g' app/build.gradle

    - name: Compilar AAB Nativo para Play Store
      run: ./gradlew clean bundleRelease

    - name: Disponibilizar AAB do Lorenzo para Download
      uses: actions/upload-artifact@v4.4.3
      with:
        name: Lorenzo-SmartWebView-AAB-Pronto
        path: app/build/outputs/bundle/release/app-release.aab
